googleAnalytics = "G-WT93QTX377"
baseURL = "https://www.harisspace.com"
languageCode = "en-us"
title = "Haris Space"
theme = "hugo-book"
params.BookTheme = "light"
googlefonts = ["Droid Sans", "Fira Mono"]
fontbody = 'Droid Sans'
fontcode = 'Fira Mono'
enableRobotsTXT = true

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
